/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiReceptionistRouteImport } from './routes/ai-receptionist'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DevApiRouteImport } from './routes/dev-api'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EnvRouteImport } from './routes/env'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyFlowsRouteImport } from './routes/my-flows'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as DocsApiKeysRouteImport } from './routes/docs.api-keys'
import { Route as DocsAutomationsRouteImport } from './routes/docs.automations'
import { Route as DocsContactsRouteImport } from './routes/docs.contacts'
import { Route as DocsDeveloperApiRouteImport } from './routes/docs.developer-api'
import { Route as DocsFlowsRouteImport } from './routes/docs.flows'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsProjectsRouteImport } from './routes/docs.projects'
import { Route as DocsSitesRouteImport } from './routes/docs.sites'
import { Route as DocsSurveysRouteImport } from './routes/docs.surveys'
import { Route as DocsTemplatesRouteImport } from './routes/docs.templates'
import { Route as DocsTicketsRouteImport } from './routes/docs.tickets'
import { Route as DocsVoiceRouteImport } from './routes/docs.voice'
import { Route as SIdRouteImport } from './routes/s.$id'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiReceptionistRoute = AiReceptionistRouteImport.update({
  id: '/ai-receptionist',
  path: '/ai-receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DevApiRoute = DevApiRouteImport.update({
  id: '/dev-api',
  path: '/dev-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvRoute = EnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFlowsRoute = MyFlowsRouteImport.update({
  id: '/my-flows',
  path: '/my-flows',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiKeysRoute = DocsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAutomationsRoute = DocsAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsContactsRoute = DocsContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDeveloperApiRoute = DocsDeveloperApiRouteImport.update({
  id: '/developer-api',
  path: '/developer-api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsFlowsRoute = DocsFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProjectsRoute = DocsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSitesRoute = DocsSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSurveysRoute = DocsSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTemplatesRoute = DocsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTicketsRoute = DocsTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DocsRoute,
} as any)
const DocsVoiceRoute = DocsVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => DocsRoute,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-receptionist': typeof AiReceptionistRoute
  '/api-keys': typeof ApiKeysRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/dev-api': typeof DevApiRoute
  '/docs': typeof DocsRouteWithChildren
  '/env': typeof EnvRoute
  '/flows': typeof FlowsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-flows': typeof MyFlowsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sites': typeof SitesRoute
  '/surveys': typeof SurveysRoute
  '/templates': typeof TemplatesRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/voice': typeof VoiceRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/automations': typeof DocsAutomationsRoute
  '/docs/contacts': typeof DocsContactsRoute
  '/docs/developer-api': typeof DocsDeveloperApiRoute
  '/docs/flows': typeof DocsFlowsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/projects': typeof DocsProjectsRoute
  '/docs/sites': typeof DocsSitesRoute
  '/docs/surveys': typeof DocsSurveysRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/tickets': typeof DocsTicketsRoute
  '/docs/voice': typeof DocsVoiceRoute
  '/s/$id': typeof SIdRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-receptionist': typeof AiReceptionistRoute
  '/api-keys': typeof ApiKeysRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/dev-api': typeof DevApiRoute
  '/docs': typeof DocsRouteWithChildren
  '/env': typeof EnvRoute
  '/flows': typeof FlowsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-flows': typeof MyFlowsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sites': typeof SitesRoute
  '/surveys': typeof SurveysRoute
  '/templates': typeof TemplatesRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/voice': typeof VoiceRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/automations': typeof DocsAutomationsRoute
  '/docs/contacts': typeof DocsContactsRoute
  '/docs/developer-api': typeof DocsDeveloperApiRoute
  '/docs/flows': typeof DocsFlowsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/projects': typeof DocsProjectsRoute
  '/docs/sites': typeof DocsSitesRoute
  '/docs/surveys': typeof DocsSurveysRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/tickets': typeof DocsTicketsRoute
  '/docs/voice': typeof DocsVoiceRoute
  '/s/$id': typeof SIdRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-receptionist': typeof AiReceptionistRoute
  '/api-keys': typeof ApiKeysRoute
  '/automations': typeof AutomationsRoute
  '/campaigns': typeof CampaignsRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/dev-api': typeof DevApiRoute
  '/docs': typeof DocsRouteWithChildren
  '/env': typeof EnvRoute
  '/flows': typeof FlowsRoute
  '/integrations': typeof IntegrationsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/my-flows': typeof MyFlowsRoute
  '/playground': typeof PlaygroundRoute
  '/projects': typeof ProjectsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sites': typeof SitesRoute
  '/surveys': typeof SurveysRoute
  '/templates': typeof TemplatesRoute
  '/tickets': typeof TicketsRoute
  '/users': typeof UsersRoute
  '/voice': typeof VoiceRoute
  '/docs/api-keys': typeof DocsApiKeysRoute
  '/docs/automations': typeof DocsAutomationsRoute
  '/docs/contacts': typeof DocsContactsRoute
  '/docs/developer-api': typeof DocsDeveloperApiRoute
  '/docs/flows': typeof DocsFlowsRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/projects': typeof DocsProjectsRoute
  '/docs/sites': typeof DocsSitesRoute
  '/docs/surveys': typeof DocsSurveysRoute
  '/docs/templates': typeof DocsTemplatesRoute
  '/docs/tickets': typeof DocsTicketsRoute
  '/docs/voice': typeof DocsVoiceRoute
  '/s/$id': typeof SIdRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-receptionist'
    | '/api-keys'
    | '/automations'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/departments'
    | '/dev-api'
    | '/docs'
    | '/env'
    | '/flows'
    | '/integrations'
    | '/login'
    | '/messages'
    | '/my-flows'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/sites'
    | '/surveys'
    | '/templates'
    | '/tickets'
    | '/users'
    | '/voice'
    | '/docs/api-keys'
    | '/docs/automations'
    | '/docs/contacts'
    | '/docs/developer-api'
    | '/docs/flows'
    | '/docs/getting-started'
    | '/docs/projects'
    | '/docs/sites'
    | '/docs/surveys'
    | '/docs/templates'
    | '/docs/tickets'
    | '/docs/voice'
    | '/s/$id'
    | '/site/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-receptionist'
    | '/api-keys'
    | '/automations'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/departments'
    | '/dev-api'
    | '/docs'
    | '/env'
    | '/flows'
    | '/integrations'
    | '/login'
    | '/messages'
    | '/my-flows'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/sites'
    | '/surveys'
    | '/templates'
    | '/tickets'
    | '/users'
    | '/voice'
    | '/docs/api-keys'
    | '/docs/automations'
    | '/docs/contacts'
    | '/docs/developer-api'
    | '/docs/flows'
    | '/docs/getting-started'
    | '/docs/projects'
    | '/docs/sites'
    | '/docs/surveys'
    | '/docs/templates'
    | '/docs/tickets'
    | '/docs/voice'
    | '/s/$id'
    | '/site/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-receptionist'
    | '/api-keys'
    | '/automations'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/departments'
    | '/dev-api'
    | '/docs'
    | '/env'
    | '/flows'
    | '/integrations'
    | '/login'
    | '/messages'
    | '/my-flows'
    | '/playground'
    | '/projects'
    | '/settings'
    | '/signup'
    | '/sites'
    | '/surveys'
    | '/templates'
    | '/tickets'
    | '/users'
    | '/voice'
    | '/docs/api-keys'
    | '/docs/automations'
    | '/docs/contacts'
    | '/docs/developer-api'
    | '/docs/flows'
    | '/docs/getting-started'
    | '/docs/projects'
    | '/docs/sites'
    | '/docs/surveys'
    | '/docs/templates'
    | '/docs/tickets'
    | '/docs/voice'
    | '/s/$id'
    | '/site/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiReceptionistRoute: typeof AiReceptionistRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AutomationsRoute: typeof AutomationsRoute
  CampaignsRoute: typeof CampaignsRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DevApiRoute: typeof DevApiRoute
  DocsRoute: typeof DocsRouteWithChildren
  EnvRoute: typeof EnvRoute
  FlowsRoute: typeof FlowsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MyFlowsRoute: typeof MyFlowsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProjectsRoute: typeof ProjectsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitesRoute: typeof SitesRoute
  SurveysRoute: typeof SurveysRoute
  TemplatesRoute: typeof TemplatesRoute
  TicketsRoute: typeof TicketsRoute
  UsersRoute: typeof UsersRoute
  VoiceRoute: typeof VoiceRoute
  SIdRoute: typeof SIdRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-receptionist': {
      id: '/ai-receptionist'
      path: '/ai-receptionist'
      fullPath: '/ai-receptionist'
      preLoaderRoute: typeof AiReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-api': {
      id: '/dev-api'
      path: '/dev-api'
      fullPath: '/dev-api'
      preLoaderRoute: typeof DevApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env': {
      id: '/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof EnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-flows': {
      id: '/my-flows'
      path: '/my-flows'
      fullPath: '/my-flows'
      preLoaderRoute: typeof MyFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api-keys': {
      id: '/docs/api-keys'
      path: '/api-keys'
      fullPath: '/docs/api-keys'
      preLoaderRoute: typeof DocsApiKeysRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/automations': {
      id: '/docs/automations'
      path: '/automations'
      fullPath: '/docs/automations'
      preLoaderRoute: typeof DocsAutomationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/contacts': {
      id: '/docs/contacts'
      path: '/contacts'
      fullPath: '/docs/contacts'
      preLoaderRoute: typeof DocsContactsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/developer-api': {
      id: '/docs/developer-api'
      path: '/developer-api'
      fullPath: '/docs/developer-api'
      preLoaderRoute: typeof DocsDeveloperApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/flows': {
      id: '/docs/flows'
      path: '/flows'
      fullPath: '/docs/flows'
      preLoaderRoute: typeof DocsFlowsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/projects': {
      id: '/docs/projects'
      path: '/projects'
      fullPath: '/docs/projects'
      preLoaderRoute: typeof DocsProjectsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/sites': {
      id: '/docs/sites'
      path: '/sites'
      fullPath: '/docs/sites'
      preLoaderRoute: typeof DocsSitesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/surveys': {
      id: '/docs/surveys'
      path: '/surveys'
      fullPath: '/docs/surveys'
      preLoaderRoute: typeof DocsSurveysRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/templates': {
      id: '/docs/templates'
      path: '/templates'
      fullPath: '/docs/templates'
      preLoaderRoute: typeof DocsTemplatesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tickets': {
      id: '/docs/tickets'
      path: '/tickets'
      fullPath: '/docs/tickets'
      preLoaderRoute: typeof DocsTicketsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/voice': {
      id: '/docs/voice'
      path: '/voice'
      fullPath: '/docs/voice'
      preLoaderRoute: typeof DocsVoiceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsApiKeysRoute: typeof DocsApiKeysRoute
  DocsAutomationsRoute: typeof DocsAutomationsRoute
  DocsContactsRoute: typeof DocsContactsRoute
  DocsDeveloperApiRoute: typeof DocsDeveloperApiRoute
  DocsFlowsRoute: typeof DocsFlowsRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsProjectsRoute: typeof DocsProjectsRoute
  DocsSitesRoute: typeof DocsSitesRoute
  DocsSurveysRoute: typeof DocsSurveysRoute
  DocsTemplatesRoute: typeof DocsTemplatesRoute
  DocsTicketsRoute: typeof DocsTicketsRoute
  DocsVoiceRoute: typeof DocsVoiceRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiKeysRoute: DocsApiKeysRoute,
  DocsAutomationsRoute: DocsAutomationsRoute,
  DocsContactsRoute: DocsContactsRoute,
  DocsDeveloperApiRoute: DocsDeveloperApiRoute,
  DocsFlowsRoute: DocsFlowsRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsProjectsRoute: DocsProjectsRoute,
  DocsSitesRoute: DocsSitesRoute,
  DocsSurveysRoute: DocsSurveysRoute,
  DocsTemplatesRoute: DocsTemplatesRoute,
  DocsTicketsRoute: DocsTicketsRoute,
  DocsVoiceRoute: DocsVoiceRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiReceptionistRoute: AiReceptionistRoute,
  ApiKeysRoute: ApiKeysRoute,
  AutomationsRoute: AutomationsRoute,
  CampaignsRoute: CampaignsRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  DevApiRoute: DevApiRoute,
  DocsRoute: DocsRouteWithChildren,
  EnvRoute: EnvRoute,
  FlowsRoute: FlowsRoute,
  IntegrationsRoute: IntegrationsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MyFlowsRoute: MyFlowsRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProjectsRoute: ProjectsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitesRoute: SitesRoute,
  SurveysRoute: SurveysRoute,
  TemplatesRoute: TemplatesRoute,
  TicketsRoute: TicketsRoute,
  UsersRoute: UsersRoute,
  VoiceRoute: VoiceRoute,
  SIdRoute: SIdRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
